# Generated by Django 3.1.3 on 2023-09-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check', models.BooleanField(default=False)),
                ('subject', models.CharField(max_length=20)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('award', models.TextField(choices=[('대상', '대상'), ('금상', '금상'), ('은상', '은상'), ('동상', '동상'), ('장려상', '장려상'), ('참가', '참가'), ('', '공백')])),
                ('content', models.CharField(max_length=20)),
                ('create_date', models.DateTimeField(auto_now=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
