# Generated by Django 3.1.3 on 2023-09-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='award',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.TextField(),
        ),
    ]
