# Generated by Django 3.1.3 on 2023-09-10 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spec', '0003_auto_20230910_2106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='end_date',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='start_date',
            field=models.TextField(),
        ),
    ]
